### ISSUE TITLE
server-fs: the crate's tests do not compile on their own

### ISSUE THREAD

**Issue by baslr** [AuDHSOS/AuDHSOS#221]
`crates/user/servers/fs/Cargo.toml:15-23` lists `fs-fat` without the `test-doubles` feature and no `fs-fat` dev-dependency, while `crates/user/servers/fs/src/tests/support.rs:7`, `crates/user/servers/fs/src/tests/serve.rs:11` and `crates/user/servers/fs/src/tests/volume.rs:7` import `fs_fat::doubles::RamDisk`, which `crates/fs/fat/src/lib.rs:11-12` compiles only under `test` or `test-doubles`.

`cargo test -p server-fs` fails with three `E0432: unresolved import fs_fat::doubles` errors. `cargo test -p server-fs -p fs-gpt` passes 43 tests because `crates/fs/gpt/Cargo.toml:16-18` enables the feature and resolver 3 (`Cargo.toml:5`) unifies it. The row at `docs/05-code-organization.md:193` lists `test-support` as the only dev-dependency.

Fix: add `fs-fat = { workspace = true, features = ["test-doubles"] }` under `[dev-dependencies]` as `fs-gpt` does, and name it in the docs/05 row.
